import type { LuxuryMuslimahTemplate } from './luxuryMuslimahTemplate';

export const modernConversionTemplate: LuxuryMuslimahTemplate = {
  id: 'modern-conversion-luxe',
  name: 'Lumiere Momentum',
  niche: 'Conversion-focused Muslimah fashion, beauty, perfume, and lifestyle products',
  mood: 'Premium, scalable, minimal luxury commerce built for high conversion',
  sections: [
    'header',
    'hero',
    'trendingCollections',
    'bestSellers',
    'flashSale',
    'socialProof',
    'productShowcase',
    'brandTrust',
    'faqNewsletter',
    'productPage',
    'cartDrawer',
    'checkout',
    'customerAccount',
  ],
  editableFields: [
    { key: 'logoText', label: 'Logo text', group: 'Brand' },
    { key: 'announcementText', label: 'Announcement text', group: 'Brand' },
    { key: 'heroHeading', label: 'Hero heading', group: 'Hero' },
    { key: 'heroSubtitle', label: 'Hero subtitle', group: 'Hero' },
    { key: 'heroImage', label: 'Hero image', group: 'Hero' },
    { key: 'collectionTiles', label: 'Trending collections', group: 'Products' },
    { key: 'productCards', label: 'Conversion product cards', group: 'Products' },
    { key: 'checkoutFields', label: 'Mobile-first checkout', group: 'Checkout' },
    { key: 'accountModules', label: 'Customer dashboard', group: 'Account' },
  ],
  collections: ['Tudung', 'Abaya', 'Beauty', 'Perfume', 'Accessories', 'Flash Deals'],
  bestSellers: [
    {
      name: 'Momentum Satin Shawl',
      category: 'Tudung',
      price: 'MYR 79',
      badge: '-20%',
      image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=80',
      colors: ['#f7eee4', '#d5b89d', '#211713'],
    },
    {
      name: 'Noir Modest Set',
      category: 'Fashion',
      price: 'MYR 259',
      badge: 'Best Seller',
      image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=900&q=80',
      colors: ['#fff8ee', '#b79b7c', '#111111'],
    },
    {
      name: 'Champagne Glow Serum',
      category: 'Beauty',
      price: 'MYR 149',
      badge: 'New',
      image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80',
      colors: ['#fbf4ea', '#d8b979', '#8f7658'],
    },
    {
      name: 'Musk Noir Parfum',
      category: 'Perfume',
      price: 'MYR 189',
      image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
      colors: ['#f5eadc', '#c9a76d', '#241915'],
    },
  ],
  trending: [
    {
      name: 'Ivory Active Inner',
      category: 'Essentials',
      price: 'MYR 69',
      badge: 'Bundle',
      image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
      colors: ['#fffaf2', '#d8c2a4', '#2a211d'],
    },
    {
      name: 'Velvet Nude Lip Cream',
      category: 'Cosmetics',
      price: 'MYR 55',
      badge: 'Hot',
      image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80',
      colors: ['#d9a18f', '#a65c55', '#f4d6ca'],
    },
    {
      name: 'Everyday Luxe Tote',
      category: 'Accessories',
      price: 'MYR 129',
      image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80',
      colors: ['#eee0cf', '#b79575', '#18120f'],
    },
    {
      name: 'Radiant Gift Set',
      category: 'Beauty',
      price: 'MYR 199',
      badge: 'Gift',
      image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
      colors: ['#f8efe2', '#d4ae68', '#594635'],
    },
  ],
};
