import type { LuxuryMuslimahTemplate } from './luxuryMuslimahTemplate';

export const softFeminineTemplate: LuxuryMuslimahTemplate = {
  id: 'soft-feminine-luxe',
  name: 'Aurelia Muse',
  niche: 'Soft feminine fashion, beauty, perfume, and lifestyle products',
  mood: 'Emotional, feminine, premium, cozy luxury commerce',
  sections: [
    'header',
    'hero',
    'categories',
    'bestSellers',
    'limitedCollection',
    'reviews',
    'fashionInspiration',
    'newsletter',
    'productPage',
    'cartDrawer',
    'checkout',
    'customerAccount',
  ],
  editableFields: [
    { key: 'logoText', label: 'Logo text', group: 'Brand' },
    { key: 'announcementText', label: 'Announcement text', group: 'Brand' },
    { key: 'heroHeading', label: 'Hero heading', group: 'Hero' },
    { key: 'heroSubtitle', label: 'Hero subtitle', group: 'Hero' },
    { key: 'heroImage', label: 'Hero image', group: 'Hero' },
    { key: 'collectionTiles', label: 'Category cards', group: 'Products' },
    { key: 'productCards', label: 'Best seller products', group: 'Products' },
    { key: 'checkoutFields', label: 'Luxury checkout', group: 'Checkout' },
    { key: 'accountModules', label: 'Account modules', group: 'Account' },
  ],
  collections: ['Tudung', 'Dresses', 'Sets', 'Perfume', 'Makeup', 'Accessories'],
  bestSellers: [
    {
      name: 'Nude Satin Shawl',
      category: 'Tudung',
      price: 'MYR 79',
      badge: 'Loved',
      image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=80',
      colors: ['#f4dfd5', '#c9a690', '#fffaf5'],
    },
    {
      name: 'Muse Cream Dress',
      category: 'Dresses',
      price: 'MYR 249',
      badge: 'Best Seller',
      image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
      colors: ['#f6eee7', '#d6b9a6', '#7b6659'],
    },
    {
      name: 'Blush Ritual Lipmatte',
      category: 'Makeup',
      price: 'MYR 55',
      image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80',
      colors: ['#d9928d', '#b96f70', '#f3c8bc'],
    },
    {
      name: 'Velvet Aura Perfume',
      category: 'Perfume',
      price: 'MYR 169',
      image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
      colors: ['#f7eee5', '#c8a077', '#8d7362'],
    },
  ],
  trending: [
    {
      name: 'Soft Taupe Co-ord',
      category: 'Sets',
      price: 'MYR 219',
      badge: 'Limited',
      image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=900&q=80',
      colors: ['#d7b9aa', '#f4ede7', '#8c7467'],
    },
    {
      name: 'Ivory Glow Skincare',
      category: 'Skincare',
      price: 'MYR 189',
      image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80',
      colors: ['#fff6ee', '#e0bda7', '#b88d72'],
    },
    {
      name: 'Muse Everyday Tote',
      category: 'Accessories',
      price: 'MYR 129',
      image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80',
      colors: ['#efe0d2', '#bb9881', '#6f5a4d'],
    },
    {
      name: 'Rose Veil Mist',
      category: 'Perfume',
      price: 'MYR 99',
      image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
      colors: ['#f5d6cf', '#e9b0a3', '#fff8f4'],
    },
  ],
};
