import type {
  ApiKeyItem,
  CourierProvider,
  IntegrationItem,
  ManualMethod,
  PaymentGateway,
  PaymentRule,
  RoleCard,
  SettingsHubCard,
  ShippingRoutingRule,
  ShippingProviderIntegration,
  ShippingZone,
  TeamMember,
  WebhookItem,
} from './types';

export const settingsHubCards: SettingsHubCard[] = [
  {
    key: 'general',
    title: 'General',
    description: 'Store identity, contact, regional settings, and default system behavior.',
    group: 'Store Setup',
  },
  {
    key: 'checkout',
    title: 'Checkout',
    description: 'Customer form, shipping/payment structure, summary logic, and add-ons.',
    group: 'Store Setup',
  },
  {
    key: 'domain-branding',
    title: 'Domain & Branding',
    description: 'Domain connection, logos, theme colors, and storefront preview sync.',
    group: 'Store Setup',
  },
  {
    key: 'payments',
    title: 'Payments',
    description: 'Gateways, manual methods, rules engine, and payment controls.',
    group: 'Commerce',
  },
  {
    key: 'shipping-logistics',
    title: 'Shipping & Logistics',
    description: 'Zones, methods, courier APIs, routing rules, and shipment simulation.',
    group: 'Commerce',
  },
  {
    key: 'notifications',
    title: 'Notifications',
    description: 'Shipment and order notifications with Email, SMS, WhatsApp, and AI timing.',
    group: 'Communication',
  },
  {
    key: 'integrations',
    title: 'Integrations',
    description: 'Tracking, messaging, and developer integrations in one operational hub.',
    group: 'Communication',
  },
  {
    key: 'staff-roles',
    title: 'Staff & Roles',
    description: 'Team members, roles, permission matrix, and account activity.',
    group: 'System Control',
  },
  {
    key: 'developer',
    title: 'Developer',
    description: 'API keys, webhooks, logs, and test console for system integration.',
    group: 'System Control',
  },
];

export const paymentGatewaysSeed: PaymentGateway[] = [
  { id: 'pg-1', slug: 'securepay', name: 'SecurePay', checkoutLabel: 'Online Payment FPX', status: 'Connected', mode: 'Live', health: 99.8, enabledAtCheckout: true, setupStage: 'Live' },
  { id: 'pg-2', slug: 'stripe', name: 'Stripe', checkoutLabel: 'Stripe', status: 'Connected', mode: 'Live', health: 99.5, enabledAtCheckout: true, setupStage: 'Live' },
  { id: 'pg-3', slug: 'paypal', name: 'PayPal', checkoutLabel: 'PayPal', status: 'Pending', mode: 'Test', health: 93.1, enabledAtCheckout: false, setupStage: 'Awaiting Approval' },
  { id: 'pg-4', slug: 'grabpay', name: 'GrabPay', checkoutLabel: 'GrabPay', status: 'Disconnected', mode: 'Test', health: 91.2, enabledAtCheckout: false, setupStage: 'Not Started' },
  { id: 'pg-5', slug: 'atome', name: 'Atome', checkoutLabel: 'Atome PayLater - 3 easy payments, 0% interest', status: 'Disconnected', mode: 'Test', health: 89.6, enabledAtCheckout: false, setupStage: 'Not Started' },
  { id: 'pg-6', slug: 'tng-ewallet', name: 'Touch n Go eWallet', checkoutLabel: 'Touch n Go eWallet', status: 'Disconnected', mode: 'Test', health: 92.4, enabledAtCheckout: false, setupStage: 'Not Started' },
  { id: 'pg-7', slug: 'fpx', name: 'FPX', checkoutLabel: 'FPX Online Banking', status: 'Disconnected', mode: 'Test', health: 94.2, enabledAtCheckout: false, setupStage: 'Not Started' },
  { id: 'pg-8', slug: 'duitnow-qr', name: 'DuitNow QR', checkoutLabel: 'DuitNow QR', status: 'Disconnected', mode: 'Test', health: 95.1, enabledAtCheckout: false, setupStage: 'Not Started' },
];

export const manualMethodsSeed: ManualMethod[] = [
  {
    id: 'mm-1',
    slug: 'cod',
    name: 'Cash on Delivery',
    enabled: true,
    description: 'Useful as a fallback for selected zones and lower-risk orders.',
    operationalUse: 'Best for local zones, trusted customer segments, or seller-assisted delivery operations.',
    customerExpectation: 'Customer chooses COD at checkout and pays only when parcel arrives or when rider confirms collection.',
    paymentStatusLabel: 'Awaiting collection on delivery',
    trackingMode: 'Track by delivery milestone and courier/rider collection confirmation.',
    proofRequired: true,
    proofChecklist: ['Delivery marked completed', 'Courier/rider collection confirmation', 'Cash handoff reference or rider note'],
    orderFlow: ['Order placed with COD selected', 'Order stays unpaid while fulfillment is prepared', 'Rider/courier collects payment', 'Ops confirms collection before closing payment as received'],
    caution: 'Do not treat COD as paid at checkout. Payment is only collected later during delivery or handoff.',
  },
  {
    id: 'mm-2',
    slug: 'bank-transfer',
    name: 'Bank Transfer',
    enabled: false,
    description: 'Useful for invoice-style or manual approval-based checkout flows.',
    operationalUse: 'Best when seller wants customer to transfer manually and submit proof before the order is approved.',
    customerExpectation: 'Customer receives transfer instructions, makes payment outside the gateway, then uploads or sends proof for review.',
    paymentStatusLabel: 'Awaiting transfer proof / verification',
    trackingMode: 'Track by uploaded receipt, bank reference, finance review, and manual approval.',
    proofRequired: true,
    proofChecklist: ['Customer receipt or transfer slip', 'Bank transaction reference', 'Matched amount and payer details'],
    orderFlow: ['Order placed with bank transfer selected', 'Order stays pending payment review', 'Customer submits transfer proof', 'Ops/finance verifies transfer before marking the order paid'],
    caution: 'Do not auto-mark bank transfer orders as paid. A human review or verified reconciliation step is still required.',
  },
];

export const paymentRulesSeed: PaymentRule[] = [
  {
    id: 'pr-1',
    name: 'High Value Secure',
    condition: 'Cart > RM 1,000',
    action: 'Force Card / Online Banking',
    status: 'Active',
  },
  {
    id: 'pr-2',
    name: 'VIP Premium Route',
    condition: 'Customer tag = VIP',
    action: 'Prioritize Stripe',
    status: 'Active',
  },
  {
    id: 'pr-3',
    name: 'Night COD Block',
    condition: '22:00 - 06:00',
    action: 'Disable COD',
    status: 'Draft',
  },
];

export const shippingZonesSeed: ShippingZone[] = [
  {
    id: 'sz-1',
    name: 'Semenanjung',
    regions: ['Johor', 'Kedah', 'Kelantan', 'Kuala Lumpur', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Perak', 'Perlis', 'Pulau Pinang', 'Putrajaya', 'Selangor', 'Terengganu'],
    methods: ['J&T EXPRESS (2-3 working days)', 'Standard Delivery', 'Express Delivery'],
    weightRates: [{ id: 'wr-1', name: 'J&T EXPRESS (2-3 working days)', range: '0.10kg - 5.00kg', rate: 'MYR6.00' }],
    priceRates: [{ id: 'pr-1', name: 'J&T EXPRESS (2-3 working days)', range: 'MYR160.00 - MYR2,000.00', rate: 'FREE' }],
  },
  {
    id: 'sz-2',
    name: 'Sabah & Sarawak',
    regions: ['Labuan', 'Sabah', 'Sarawak'],
    methods: ['Poslaju (3-5 working days)', 'J&T EXPRESS (3-5 working days)'],
    weightRates: [{ id: 'wr-2', name: 'Poslaju (3-5 working days)', range: '0.10kg - 5.00kg', rate: 'MYR14.00' }],
    priceRates: [{ id: 'pr-2', name: 'J&T EXPRESS (3-5 working days)', range: 'MYR160.00 - MYR1,000.00', rate: 'FREE' }],
  },
];

export const courierProvidersSeed: CourierProvider[] = [
  {
    id: 'cp-1',
    slug: 'jt-express',
    name: 'J&T',
    status: 'Connected',
    mode: 'Live',
    enabledForRouting: true,
    setupStage: 'Live',
    description: 'Common Malaysia courier option for fast local delivery coverage and familiar e-commerce fulfillment flow.',
    sellerFit: 'Good for stores that want strong local fulfillment coverage and simple domestic shipping operations.',
    requirements: ['Approved J&T shipper account', 'Merchant API or dashboard credentials', 'Pickup contact and warehouse details', 'Tracking sync readiness'],
    onboardingItems: ['Apply as shipper / merchant', 'Complete account onboarding', 'Add credentials and pickup contact', 'Test tracking and shipment sync before live routing'],
    syncFlow: 'Bisora creates shipment request, stores courier reference, then updates fulfillment timeline when J&T tracking events are received.',
    applyUrl: 'https://www.jtexpress.my/',
    infoUrl: 'https://www.jtexpress.my/',
    trackingUrl: 'https://www.jtexpress.my/',
  },
  {
    id: 'cp-2',
    slug: 'dhl-ecommerce',
    name: 'DHL eCommerce',
    status: 'Sandbox',
    mode: 'Test',
    enabledForRouting: false,
    setupStage: 'Ready to Connect',
    description: 'Useful when you need structured eCommerce delivery operations and international-ready shipping support.',
    sellerFit: 'Good for stores preparing more structured domestic plus cross-border fulfillment workflows.',
    requirements: ['DHL eCommerce business account', 'Sandbox or production credentials', 'Pickup origin details', 'Service mapping / rate testing'],
    onboardingItems: ['Open DHL eCommerce account', 'Receive sandbox or onboarding credentials', 'Map pickup and service setup', 'Run test shipment sync before going live'],
    syncFlow: 'Bisora submits shipment request, courier returns service response and tracking ID, then shipping events should update order fulfillment visibility.',
    applyUrl: 'https://www.dhl.com/my-en/home/our-divisions/ecommerce.html',
    infoUrl: 'https://www.dhl.com/discover/en-my/logistics-advice/import-export-advice/dhl-ecommerce-solutions',
    trackingUrl: 'https://www.dhl.com/my-en/home/tracking.html',
  },
  {
    id: 'cp-3',
    slug: 'dhl-express',
    name: 'DHL Express',
    status: 'Disconnected',
    mode: 'Test',
    enabledForRouting: false,
    setupStage: 'Not Started',
    description: 'Premium express courier path for faster international or time-sensitive shipments.',
    sellerFit: 'Good when seller needs stronger SLA, cross-border express service, and premium shipping expectations.',
    requirements: ['DHL Express account', 'Shipping account credentials', 'Declared pickup origin', 'Customs / express shipment readiness'],
    onboardingItems: ['Open DHL Express account', 'Get account approval and credentials', 'Configure pickup and shipment options', 'Test label and tracking flow before live use'],
    syncFlow: 'Bisora sends express shipment request, receives airwaybill / tracking details, then updates tracking milestones through courier events.',
    applyUrl: 'https://www.dhl.com/my-en/home/our-divisions/express.html',
    infoUrl: 'https://www.dhl.com/my-en/home/our-divisions/express/shipping.html',
    trackingUrl: 'https://www.dhl.com/my-en/home/tracking.html',
  },
  {
    id: 'cp-4',
    slug: 'ninja-van',
    name: 'Ninja Van',
    status: 'Connected',
    mode: 'Live',
    enabledForRouting: true,
    setupStage: 'Live',
    description: 'Popular domestic courier option for Malaysia-first fulfillment and reliable operational coverage.',
    sellerFit: 'Good for stores that want broad Malaysia coverage, pickup scheduling, and familiar fulfillment flow.',
    requirements: ['Approved Ninja Van shipper account', 'API credentials / account access', 'Pickup address and contact', 'Label and tracking sync readiness'],
    onboardingItems: ['Register shipper account', 'Get account approval and onboarding access', 'Add API credentials and pickup contact', 'Test label creation and live tracking sync'],
    syncFlow: 'Bisora sends shipment data, courier creates shipment / label, tracking number is returned, and fulfillment timeline updates from courier tracking events.',
    applyUrl: 'https://www.ninjavan.co/en-my',
    infoUrl: 'https://www.ninjavan.co/en-my/business',
    trackingUrl: 'https://www.ninjavan.co/en-my/tracking',
  },
  {
    id: 'cp-5',
    slug: 'ninja-van-international',
    name: 'Ninja Van International',
    status: 'Disconnected',
    mode: 'Test',
    enabledForRouting: false,
    setupStage: 'Not Started',
    description: 'International extension for sellers who want to keep Ninja Van style operations for cross-border flows.',
    sellerFit: 'Good for stores expanding outside Malaysia but wanting a familiar logistics partner pattern.',
    requirements: ['International shipping account support', 'Cross-border onboarding path', 'Origin and customs data readiness', 'Tracking sync capability'],
    onboardingItems: ['Contact Ninja Van international onboarding', 'Confirm supported destination lanes', 'Prepare customs / shipment data fields', 'Run test sync before live rollout'],
    syncFlow: 'Bisora prepares international shipment payload, courier returns tracking reference, and seller monitors milestone updates across cross-border flow.',
    applyUrl: 'https://www.ninjavan.co/en-my/business',
    infoUrl: 'https://www.ninjavan.co/en-my/business',
    trackingUrl: 'https://www.ninjavan.co/en-my/tracking',
  },
  {
    id: 'cp-6',
    slug: 'pos-malaysia',
    name: 'POS Malaysia',
    status: 'Disconnected',
    mode: 'Test',
    enabledForRouting: false,
    setupStage: 'Applied',
    description: 'Trusted Malaysia postal and logistics path for broad domestic delivery expectations.',
    sellerFit: 'Good for stores that want a familiar nationwide courier / postal fallback.',
    requirements: ['Pos Malaysia business onboarding', 'Account access', 'Pickup / drop-off workflow decision', 'Tracking visibility'],
    onboardingItems: ['Register business shipping access', 'Confirm service option and onboarding path', 'Add account / service details', 'Validate shipment and tracking updates before routing'],
    syncFlow: 'Bisora creates shipment record, stores courier tracking reference, and updates seller visibility as Pos Malaysia events are synced.',
    applyUrl: 'https://www.pos.com.my/',
    infoUrl: 'https://www.pos.com.my/business/solutions/logistics',
    trackingUrl: 'https://www.pos.com.my/send/ratecalculator',
  },
  {
    id: 'cp-7',
    slug: 'gdex',
    name: 'GDEX',
    status: 'Disconnected',
    mode: 'Test',
    enabledForRouting: false,
    setupStage: 'Not Started',
    description: 'Local courier alternative for stores that want another domestic routing and fulfillment fallback.',
    sellerFit: 'Good as a secondary local courier when seller wants more routing flexibility.',
    requirements: ['GDEX merchant account', 'Credential access', 'Pickup contact details', 'Tracking update readiness'],
    onboardingItems: ['Apply for merchant shipping setup', 'Receive account details and credentials', 'Configure pickup and test shipment flow', 'Verify tracking sync before activation'],
    syncFlow: 'Bisora creates shipment entry, receives GDEX reference / tracking output, and updates fulfillment milestones from courier sync.',
    applyUrl: 'https://www.gdexpress.com/malaysia/',
    infoUrl: 'https://www.gdexpress.com/malaysia/business-solutions/',
    trackingUrl: 'https://www.gdexpress.com/malaysia/tracking/',
  },
  {
    id: 'cp-8',
    slug: 'aramex',
    name: 'Aramex',
    status: 'Disconnected',
    mode: 'Test',
    enabledForRouting: false,
    setupStage: 'Not Started',
    description: 'International logistics brand for stores that need broader regional or global delivery support.',
    sellerFit: 'Good when seller wants international-ready shipping options beyond local-only courier coverage.',
    requirements: ['Aramex business account', 'Integration credentials', 'Origin and contact setup', 'Cross-border shipment readiness'],
    onboardingItems: ['Open Aramex business account', 'Collect credentials and service onboarding support', 'Map shipment / origin details', 'Test tracking and shipment sync before enabling routing'],
    syncFlow: 'Bisora sends shipment request, receives Aramex tracking details, and updates order milestones using courier sync events.',
    applyUrl: 'https://www.aramex.com/my/en/ship',
    infoUrl: 'https://www.aramex.com/my/en/services-solutions/e-commerce',
    trackingUrl: 'https://www.aramex.com/my/en/track/shipments',
  },
];

export const shippingProviderIntegrationsSeed: ShippingProviderIntegration[] = [
  {
    id: 'spi-1',
    slug: 'easyparcel',
    name: 'Easyparcel',
    status: 'Connected',
    mode: 'Test',
    autoTracking: true,
    enabled: false,
    description: 'Delivery made easy',
    setupHint: 'Use Easyparcel when seller wants one aggregator path to compare and manage multiple courier services.',
    applyUrl: 'https://easyparcel.com/my',
    infoUrl: 'https://easyparcel.com/my/en/solutions/ecommerce',
  },
  {
    id: 'spi-2',
    slug: 'delyva',
    name: 'Delyva (Matdispatch)',
    status: 'Disabled',
    mode: 'Test',
    autoTracking: true,
    enabled: false,
    description: 'Save time & money on shipping',
    setupHint: 'Useful for operational dispatch and local logistics coordination.',
    applyUrl: 'https://delyva.io/',
    infoUrl: 'https://delyva.io/',
  },
  {
    id: 'spi-3',
    slug: 'sendparcel',
    name: 'Sendparcel by Poslaju',
    status: 'Disabled',
    mode: 'Test',
    autoTracking: true,
    enabled: false,
    description: 'Delivery rates and booking flow for online shipping',
    setupHint: 'Useful when seller wants Poslaju-related shipment booking path through a provider workflow.',
    applyUrl: 'https://www.sendparcel.com.my/',
    infoUrl: 'https://www.sendparcel.com.my/',
  },
  {
    id: 'spi-4',
    slug: 'ninjavan-optimise',
    name: 'NinjaVan Optimise',
    status: 'Disabled',
    mode: 'Test',
    autoTracking: true,
    enabled: false,
    description: 'Optimise, manage and grow with supply chain logistics solutions',
    setupHint: 'Useful when seller wants a platform-style logistics management layer from Ninja Van.',
    applyUrl: 'https://www.ninjavan.co/en-my/business',
    infoUrl: 'https://www.ninjavan.co/en-my/business',
  },
  {
    id: 'spi-5',
    slug: 'pos-malaysia-provider',
    name: 'Pos Malaysia',
    status: 'Disabled',
    mode: 'Test',
    autoTracking: true,
    enabled: false,
    description: 'Your trusted Malaysian courier and logistics provider',
    setupHint: 'Useful for seller that wants Pos Malaysia provider-based integration path.',
    applyUrl: 'https://www.pos.com.my/',
    infoUrl: 'https://www.pos.com.my/business/solutions/logistics',
  },
  {
    id: 'spi-6',
    slug: 'parcel-daily',
    name: 'ParcelDaily',
    status: 'Disabled',
    mode: 'Test',
    autoTracking: true,
    enabled: false,
    description: 'Malaysia-based delivery partner for e-commerce stores, businesses and personal use',
    setupHint: 'Useful as another Malaysia-focused delivery integration option.',
    applyUrl: 'https://www.parceldaily.com/',
    infoUrl: 'https://www.parceldaily.com/',
  },
];

export const shippingRoutingRulesSeed: ShippingRoutingRule[] = [
  {
    id: 'srr-1',
    name: 'Semenanjung Priority',
    condition: 'Zone = Semenanjung',
    action: 'Use Ninja Van first',
    status: 'Active',
  },
  {
    id: 'srr-2',
    name: 'Express Fallback',
    condition: 'Express order + primary courier unavailable',
    action: 'Fallback to DHL Express',
    status: 'Active',
  },
  {
    id: 'srr-3',
    name: 'East Malaysia Control',
    condition: 'Zone = Sabah & Sarawak',
    action: 'Prefer POS Malaysia or J&T EXPRESS (3-5 working days)',
    status: 'Draft',
  },
];

export const teamMembersSeed: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Ilena Vance',
    email: 'ilena@atelier.com',
    role: 'Store Manager',
    status: 'Active',
    avatarUrl: 'https://picsum.photos/seed/staff-ilena/72/72',
  },
  {
    id: 'tm-2',
    name: 'Julian Thorne',
    email: 'julian@atelier.com',
    role: 'Fulfillment Lead',
    status: 'Invited',
    avatarUrl: 'https://picsum.photos/seed/staff-julian/72/72',
  },
];

export const roleCards: RoleCard[] = [
  { id: 'rc-1', name: 'Owner', description: 'Full access across all operational modules and controls.' },
  { id: 'rc-2', name: 'Store Manager', description: 'Operational control for catalog, orders, and campaigns.' },
  { id: 'rc-3', name: 'Fulfillment', description: 'Packing, shipping, and courier workflow access.' },
  { id: 'rc-4', name: 'Support', description: 'Customer support visibility for order status, messaging, and issue follow-up.' },
];

export const integrationsSeed: IntegrationItem[] = [
  { id: 'in-1', name: 'Meta Pixel & CAPI', category: 'Tracking & Analytics', status: 'Connected' },
  { id: 'in-2', name: 'Google Ads', category: 'Tracking & Analytics', status: 'Not Connected' },
  { id: 'in-3', name: 'TikTok Pixel', category: 'Tracking & Analytics', status: 'Not Connected' },
  { id: 'in-4', name: 'Google Analytics 4', category: 'Tracking & Analytics', status: 'Connected' },
  { id: 'in-5', name: 'Google Tag Manager', category: 'Tracking & Analytics', status: 'Not Connected' },
  { id: 'in-6', name: 'WhatsApp Providers', category: 'Messaging', status: 'Connected' },
  { id: 'in-7', name: 'Email Providers', category: 'Messaging', status: 'Connected' },
  { id: 'in-8', name: 'SMS Providers', category: 'Messaging', status: 'Not Connected' },
  { id: 'in-9', name: 'API Keys & Access', category: 'Developer', status: 'Connected' },
  { id: 'in-10', name: 'Webhooks', category: 'Developer', status: 'Connected' },
  { id: 'in-11', name: 'Custom App / ERP Sync', category: 'Developer', status: 'Not Connected' },
];

export const apiKeysSeed: ApiKeyItem[] = [
  {
    id: 'ak-1',
    name: 'Stripe Connector',
    keyMasked: 'sk_live_xxx...42f',
    scope: 'Payments',
    createdAt: 'Oct 12, 2025',
    status: 'Active',
  },
  {
    id: 'ak-2',
    name: 'Inventory Webhook',
    keyMasked: 'ik_live_xxx...89r',
    scope: 'Products',
    createdAt: 'Jan 05, 2026',
    status: 'Active',
  },
];

export const webhooksSeed: WebhookItem[] = [
  {
    id: 'wh-1',
    endpoint: 'https://api.atelier.com/webhooks/orders',
    events: ['order.created', 'order.updated'],
    status: 'Active',
    lastDelivery: '10 mins ago',
  },
  {
    id: 'wh-2',
    endpoint: 'https://api.atelier.com/webhooks/payments',
    events: ['payment.success', 'payment.failed'],
    status: 'Paused',
    lastDelivery: 'Never',
  },
];
