import type {
  DateBreakdownRow,
  FinanceKpi,
  IntelligenceCard,
  PayoutRow,
  ProductSalesRow,
  ReconciliationRow,
  RecommendedAction,
  ReportsMetric,
  RevenuePoint,
  SettlementRow,
  TopProduct,
  TransactionRow,
  VariantSalesRow,
} from './types';

export const overviewMetrics: ReportsMetric[] = [
  { label: 'Total Revenue', value: 'RM 1,240,500', helper: '+12.3% vs last period', trend: '+12.3%', trendDirection: 'up' },
  { label: 'Total Orders', value: '8,420', helper: '+8.4% vs last period', trend: '+8.4%', trendDirection: 'up' },
  { label: 'Conversion Rate', value: '3.4%', helper: '-0.2% vs last period', trend: '-0.2%', trendDirection: 'down' },
  { label: 'Average Order Value', value: 'RM 147.30', helper: '+1.9% vs last period', trend: '+1.9%', trendDirection: 'up' },
];

export const revenuePerformance: RevenuePoint[] = [
  { label: 'W1', current: 52000, previous: 46000 },
  { label: 'W2', current: 61000, previous: 52000 },
  { label: 'W3', current: 57000, previous: 53000 },
  { label: 'W4', current: 78000, previous: 62000 },
  { label: 'W5', current: 93000, previous: 76000 },
  { label: 'W6', current: 81000, previous: 70000 },
];

export const topProducts: TopProduct[] = [
  {
    id: 'tp-1',
    name: 'Noura Silk Abaya',
    category: 'Abayas',
    imageUrl: 'https://picsum.photos/seed/reports-noura/80/80',
    revenue: 280000,
    units: 1240,
    trend: 'up',
  },
  {
    id: 'tp-2',
    name: 'Celestial Hijab',
    category: 'Hijabs',
    imageUrl: 'https://picsum.photos/seed/reports-celestial/80/80',
    revenue: 190000,
    units: 920,
    trend: 'up',
  },
  {
    id: 'tp-3',
    name: 'Raya Velvet Kaftan',
    category: 'Kaftans',
    imageUrl: 'https://picsum.photos/seed/reports-kaftan/80/80',
    revenue: 130000,
    units: 470,
    trend: 'down',
  },
];

export const dateRows: DateBreakdownRow[] = [
  { id: 'd-1', date: 'May 18, 2026', orders: 286, revenue: 64800, avgOrderValue: 226.57 },
  { id: 'd-2', date: 'May 17, 2026', orders: 312, revenue: 69200, avgOrderValue: 221.79 },
  { id: 'd-3', date: 'May 16, 2026', orders: 252, revenue: 54400, avgOrderValue: 215.87 },
  { id: 'd-4', date: 'May 15, 2026', orders: 246, revenue: 53325, avgOrderValue: 216.77 },
  { id: 'd-5', date: 'May 14, 2026', orders: 198, revenue: 41200, avgOrderValue: 208.08 },
  { id: 'd-6', date: 'May 13, 2026', orders: 174, revenue: 38880, avgOrderValue: 223.45 },
];

export const productSalesRows: ProductSalesRow[] = [
  {
    id: 'ps-1',
    rank: 1,
    name: 'Midnight Silk Abaya',
    category: 'Abayas',
    imageUrl: 'https://picsum.photos/seed/reports-ps-1/72/72',
    unitsSold: 1240,
    revenue: 280000,
    conversionRate: 4.2,
    status: 'Healthy',
  },
  {
    id: 'ps-2',
    rank: 2,
    name: 'Pearl Embroidered Wrap',
    category: 'Wraps',
    imageUrl: 'https://picsum.photos/seed/reports-ps-2/72/72',
    unitsSold: 920,
    revenue: 190000,
    conversionRate: 3.8,
    status: 'Healthy',
  },
  {
    id: 'ps-3',
    rank: 3,
    name: 'Desert Sand Gown',
    category: 'Gowns',
    imageUrl: 'https://picsum.photos/seed/reports-ps-3/72/72',
    unitsSold: 750,
    revenue: 160000,
    conversionRate: 3.1,
    status: 'Watch',
  },
  {
    id: 'ps-4',
    rank: 4,
    name: 'Raya Velvet Kaftan',
    category: 'Kaftans',
    imageUrl: 'https://picsum.photos/seed/reports-ps-4/72/72',
    unitsSold: 470,
    revenue: 130000,
    conversionRate: 2.4,
    status: 'Opportunity',
  },
];

export const variantSalesRows: VariantSalesRow[] = [
  {
    id: 'vs-1',
    productName: 'Silk Blouse',
    variant: 'Navy / L',
    sku: 'BLS-SLK-NVY-L',
    imageUrl: 'https://picsum.photos/seed/reports-vs-1/72/72',
    stock: 32,
    revenue: 18422,
    orders: 312,
    trend: 'up',
  },
  {
    id: 'vs-2',
    productName: 'Leather Tote',
    variant: 'Brown / One Size',
    sku: 'TTE-LTH-BRW-OS',
    imageUrl: 'https://picsum.photos/seed/reports-vs-2/72/72',
    stock: 8,
    revenue: 41770,
    orders: 154,
    trend: 'flat',
  },
  {
    id: 'vs-3',
    productName: 'Linen Pants',
    variant: 'Olive / M',
    sku: 'PNT-LIN-OLV-M',
    imageUrl: 'https://picsum.photos/seed/reports-vs-3/72/72',
    stock: 3,
    revenue: 12640,
    orders: 86,
    trend: 'down',
  },
];

export const intelligenceCards: IntelligenceCard[] = [
  {
    id: 'ic-1',
    title: 'Revenue Opportunities',
    summary: 'WhatsApp retention campaigns can drive +6.4% incremental recovered revenue.',
    status: 'Positive',
    cta: 'Open Strategy',
  },
  {
    id: 'ic-2',
    title: 'Performance Alerts',
    summary: 'Raya Velvet Kaftan conversion dropped below threshold in the last 7 days.',
    status: 'Warning',
    cta: 'Launch Fix',
  },
  {
    id: 'ic-3',
    title: 'Inventory Intelligence',
    summary: 'Low stock risk on top-selling variants may cause lost revenue this week.',
    status: 'Critical',
    cta: 'Review Stock',
  },
  {
    id: 'ic-4',
    title: 'Channel Intelligence',
    summary: 'Email broad campaigns are underperforming compared to segmented flows.',
    status: 'Warning',
    cta: 'Shift Budget',
  },
];

export const recommendedActionsSeed: RecommendedAction[] = [
  {
    id: 'ra-1',
    action: 'Restock Silk Blouse Navy Large',
    priority: 'High',
    category: 'Inventory',
    impact: '+RM 52k',
    status: 'Pending',
  },
  {
    id: 'ra-2',
    action: 'Increase price on top variant by 5%',
    priority: 'Medium',
    category: 'Pricing',
    impact: 'Stable AOV',
    status: 'Pending',
  },
  {
    id: 'ra-3',
    action: 'Launch Eid Week Promo',
    priority: 'Medium',
    category: 'Promotion',
    impact: '+8.3% sales',
    status: 'Pending',
  },
];

export const financeKpis: FinanceKpi[] = [
  { label: 'Cash Collected', value: 'RM 914,200', helper: 'Net captured in current payout cycle' },
  { label: 'In Settlement', value: 'RM 126,480', helper: 'Awaiting processor release' },
  { label: 'Upcoming Payouts', value: 'RM 241,900', helper: 'Across 3 scheduled transfers' },
  { label: 'Exceptions', value: '14', helper: 'Require reconciliation review' },
];

export const transactionRows: TransactionRow[] = [
  {
    id: 'tr-1',
    transactionId: 'TXN-2026-0418',
    orderId: 'ORD-84218',
    customer: 'Alya Rahman',
    customerEmail: 'alya.rahman@email.com',
    gateway: 'Stripe',
    paymentMethod: 'Card',
    status: 'Paid',
    grossAmount: 1840,
    fee: 42,
    netAmount: 1798,
    paymentDate: 'Apr 18, 2026 09:24',
    notes: '3DS authenticated successfully. Funds included in next Stripe settlement batch.',
  },
  {
    id: 'tr-2',
    transactionId: 'TXN-2026-0417',
    orderId: 'ORD-84201',
    customer: 'Nora Hamid',
    customerEmail: 'nora.hamid@email.com',
    gateway: 'SecurePay',
    paymentMethod: 'FPX',
    status: 'Paid',
    grossAmount: 720,
    fee: 11,
    netAmount: 709,
    paymentDate: 'Apr 17, 2026 18:06',
    notes: 'Bank redirect completed via SecurePay FPX. Order released to fulfillment.',
  },
  {
    id: 'tr-3',
    transactionId: 'TXN-2026-0416',
    orderId: 'ORD-84177',
    customer: 'Layla Ismail',
    customerEmail: 'layla.ismail@email.com',
    gateway: 'Stripe',
    paymentMethod: 'Wallet',
    status: 'Failed',
    grossAmount: 1320,
    fee: 26,
    netAmount: 1294,
    paymentDate: 'Apr 16, 2026 12:40',
    notes: 'Wallet authorization failed after issuer challenge timeout. Payment not captured.',
  },
  {
    id: 'tr-4',
    transactionId: 'TXN-2026-0415',
    orderId: 'ORD-84142',
    customer: 'Farah Aziz',
    customerEmail: 'farah.aziz@email.com',
    gateway: 'SecurePay',
    paymentMethod: 'Card',
    status: 'Refunded',
    grossAmount: 960,
    fee: 0,
    netAmount: 960,
    paymentDate: 'Apr 15, 2026 15:14',
    notes: 'Full refund issued after duplicate payment reported by customer.',
  },
  {
    id: 'tr-5',
    transactionId: 'TXN-2026-0414',
    orderId: 'ORD-84096',
    customer: 'Sara Zain',
    customerEmail: 'sara.zain@email.com',
    gateway: 'Stripe',
    paymentMethod: 'Card',
    status: 'Paid',
    grossAmount: 2100,
    fee: 48,
    netAmount: 2052,
    paymentDate: 'Apr 14, 2026 10:18',
    notes: 'High-value card payment settled successfully with low fraud risk score.',
  },
  {
    id: 'tr-6',
    transactionId: 'TXN-2026-0413',
    orderId: 'ORD-84081',
    customer: 'Mira Hakim',
    customerEmail: 'mira.hakim@email.com',
    gateway: 'SecurePay',
    paymentMethod: 'FPX',
    status: 'Failed',
    grossAmount: 540,
    fee: 8,
    netAmount: 532,
    paymentDate: 'Apr 13, 2026 16:52',
    notes: 'FPX session expired before bank confirmation. Customer prompted to retry checkout.',
  },
  {
    id: 'tr-7',
    transactionId: 'TXN-2026-0412',
    orderId: 'ORD-84044',
    customer: 'Huda Karim',
    customerEmail: 'huda.karim@email.com',
    gateway: 'Stripe',
    paymentMethod: 'Wallet',
    status: 'Paid',
    grossAmount: 1280,
    fee: 31,
    netAmount: 1249,
    paymentDate: 'Apr 12, 2026 14:05',
    notes: 'Apple Pay wallet payment completed in one tap on mobile storefront.',
  },
];

export const settlementRows: SettlementRow[] = [
  {
    id: 'st-1',
    settlementBatchId: 'SET-APR-18-A',
    gateway: 'Stripe',
    orderCount: 148,
    grossAmount: 186200,
    fees: 5240,
    netPayout: 180960,
    bankAccount: 'Maybank x2841',
    status: 'Settled',
    estimatedArrivalDate: 'Apr 22, 2026',
    settledDate: 'Apr 22, 2026',
    timeline: [
      { label: 'Payment collected', at: 'Apr 18, 2026 08:00', state: 'complete' },
      { label: 'Processing', at: 'Apr 19, 2026 14:20', state: 'complete' },
      { label: 'Sent to bank', at: 'Apr 21, 2026 10:15', state: 'complete' },
      { label: 'Settled', at: 'Apr 22, 2026 09:40', state: 'complete' },
    ],
  },
  {
    id: 'st-2',
    settlementBatchId: 'SET-APR-19-B',
    gateway: 'SecurePay',
    orderCount: 62,
    grossAmount: 82440,
    fees: 2412,
    netPayout: 80028,
    bankAccount: 'CIMB x9912',
    status: 'Pending',
    estimatedArrivalDate: 'Apr 24, 2026',
    settledDate: '-',
    timeline: [
      { label: 'Payment collected', at: 'Apr 19, 2026 07:30', state: 'complete' },
      { label: 'Processing', at: 'Apr 22, 2026 11:10', state: 'current' },
      { label: 'Sent to bank', at: 'Expected Apr 23, 2026', state: 'upcoming' },
      { label: 'Settled', at: 'Expected Apr 24, 2026', state: 'upcoming' },
    ],
  },
  {
    id: 'st-3',
    settlementBatchId: 'SET-APR-20-C',
    gateway: 'Stripe',
    orderCount: 51,
    grossAmount: 69400,
    fees: 1982,
    netPayout: 67418,
    bankAccount: 'Maybank x2841',
    status: 'Processing',
    estimatedArrivalDate: 'Apr 23, 2026',
    settledDate: '-',
    timeline: [
      { label: 'Payment collected', at: 'Apr 20, 2026 06:45', state: 'complete' },
      { label: 'Processing', at: 'Apr 21, 2026 13:00', state: 'current' },
      { label: 'Sent to bank', at: 'Expected Apr 22, 2026', state: 'upcoming' },
      { label: 'Settled', at: 'Expected Apr 23, 2026', state: 'upcoming' },
    ],
  },
  {
    id: 'st-4',
    settlementBatchId: 'SET-APR-21-D',
    gateway: 'SecurePay',
    orderCount: 39,
    grossAmount: 48860,
    fees: 1490,
    netPayout: 47370,
    bankAccount: 'RHB x6630',
    status: 'Pending',
    estimatedArrivalDate: 'Apr 25, 2026',
    settledDate: '-',
    timeline: [
      { label: 'Payment collected', at: 'Apr 21, 2026 09:05', state: 'complete' },
      { label: 'Processing', at: 'Queued for Apr 23, 2026', state: 'upcoming' },
      { label: 'Sent to bank', at: 'Expected Apr 24, 2026', state: 'upcoming' },
      { label: 'Settled', at: 'Expected Apr 25, 2026', state: 'upcoming' },
    ],
  },
];

export const payoutRows: PayoutRow[] = [
  {
    id: 'po-1',
    payoutId: 'PAYOUT-8421',
    gateway: 'Stripe',
    destination: 'Maybank x2841',
    initiatedAt: 'Apr 20, 2026 11:30',
    expectedAt: 'Apr 22, 2026',
    grossSales: 178400,
    fees: 5840,
    amount: 172560,
    periodLabel: 'Apr 18',
    status: 'Completed',
  },
  {
    id: 'po-2',
    payoutId: 'PAYOUT-8428',
    gateway: 'SecurePay',
    destination: 'CIMB x9912',
    initiatedAt: 'Apr 21, 2026 08:20',
    expectedAt: 'Apr 23, 2026',
    grossSales: 79420,
    fees: 2492,
    amount: 76928,
    periodLabel: 'Apr 19',
    status: 'In transit',
  },
  {
    id: 'po-3',
    payoutId: 'PAYOUT-8432',
    gateway: 'Stripe',
    destination: 'Maybank x2841',
    initiatedAt: 'Apr 21, 2026 17:45',
    expectedAt: 'Apr 24, 2026',
    grossSales: 66980,
    fees: 2262,
    amount: 64718,
    periodLabel: 'Apr 20',
    status: 'On hold',
  },
  {
    id: 'po-4',
    payoutId: 'PAYOUT-8437',
    gateway: 'SecurePay',
    destination: 'RHB x6630',
    initiatedAt: 'Apr 22, 2026 09:12',
    expectedAt: 'Apr 25, 2026',
    grossSales: 53220,
    fees: 1710,
    amount: 51510,
    periodLabel: 'Apr 21',
    status: 'In transit',
  },
  {
    id: 'po-5',
    payoutId: 'PAYOUT-8441',
    gateway: 'Stripe',
    destination: 'Maybank x2841',
    initiatedAt: 'Apr 22, 2026 18:05',
    expectedAt: 'Apr 26, 2026',
    grossSales: 48240,
    fees: 1590,
    amount: 46650,
    periodLabel: 'Apr 22',
    status: 'Completed',
  },
];

export const reconciliationRows: ReconciliationRow[] = [
  {
    id: 'rc-1',
    orderId: 'ORD-84231',
    issueType: 'Unsettled',
    amount: 1840,
    status: 'Open',
    actionLabel: 'Investigate',
    description: 'Payment was marked paid, but no settlement batch has been linked yet.',
  },
  {
    id: 'rc-2',
    orderId: 'ORD-84209',
    issueType: 'Missing',
    amount: 720,
    status: 'In review',
    actionLabel: 'Re-sync Payment',
    description: 'Order exists, but the gateway transaction record is missing from the local sync.',
  },
  {
    id: 'rc-3',
    orderId: 'ORD-84177',
    issueType: 'Failed Sync',
    amount: 1320,
    status: 'Open',
    actionLabel: 'Re-sync Payment',
    description: 'Payment update failed during sync after gateway callback timeout.',
  },
  {
    id: 'rc-4',
    orderId: 'ORD-84142',
    issueType: 'Unsettled',
    amount: 960,
    status: 'In review',
    actionLabel: 'View Order',
    description: 'Refunded order still appears in unpaid settlement records and needs validation.',
  },
  {
    id: 'rc-5',
    orderId: 'ORD-84096',
    issueType: 'Missing',
    amount: 2100,
    status: 'Resolved',
    actionLabel: 'View Order',
    description: 'Transaction was recovered after re-sync and now matches the order successfully.',
  },
];
