import type { Customer, ReviewRecord } from './types';

export const initialCustomers: Customer[] = [
  {
    id: 'cust-amara-al-said',
    name: 'Amara Al-Said',
    email: 'amara@atelier.com',
    avatarUrl: 'https://picsum.photos/seed/customer-amara/64/64',
    status: 'VIP',
    ordersCount: 12,
    totalSpent: 14250,
    lastOrderDate: 'Oct 24, 2023',
    memberSince: 'Oct 2023',
    shippingAddress: ['Villa 14, Street 102', 'Jumeirah, Dubai', 'UAE'],
    notes: ['Prefers WhatsApp for urgent updates.', 'VIP support priority.'],
    orderHistory: [
      { id: '#AT-92841', date: 'Oct 24, 2023', total: 1420, paymentStatus: 'Paid', fulfillmentStatus: 'Shipped' },
      { id: '#AT-91024', date: 'Sep 08, 2023', total: 890, paymentStatus: 'Paid', fulfillmentStatus: 'Delivered' },
      { id: '#AT-88932', date: 'Aug 23, 2023', total: 2100, paymentStatus: 'Paid', fulfillmentStatus: 'Delivered' },
    ],
    recentPurchases: [
      { id: 'pur-1', name: 'Silk Abaya - Emerald', price: 450, imageUrl: 'https://picsum.photos/seed/purchase-1/120/120' },
      { id: 'pur-2', name: 'Chiffon Wrap - Sand', price: 210, imageUrl: 'https://picsum.photos/seed/purchase-2/120/120' },
      { id: 'pur-3', name: 'Linen Palazzo Pant', price: 130, imageUrl: 'https://picsum.photos/seed/purchase-3/120/120' },
      { id: 'pur-4', name: 'Wool Coat - Camel', price: 390, imageUrl: 'https://picsum.photos/seed/purchase-4/120/120' },
    ],
  },
  {
    id: 'cust-fatima-noor',
    name: 'Fatima Noor',
    email: 'fatima@email.com',
    avatarUrl: 'https://picsum.photos/seed/customer-fatima/64/64',
    status: 'Returning',
    ordersCount: 5,
    totalSpent: 3840,
    lastOrderDate: 'Sep 29, 2023',
    memberSince: 'Jul 2023',
    shippingAddress: ['24 Jalan Tun Razak', 'Kuala Lumpur', 'Malaysia'],
    notes: ['Usually buys hijab bundles.'],
    orderHistory: [
      { id: '#AT-90111', date: 'Sep 29, 2023', total: 640, paymentStatus: 'Paid', fulfillmentStatus: 'Delivered' },
      { id: '#AT-89320', date: 'Aug 28, 2023', total: 520, paymentStatus: 'Paid', fulfillmentStatus: 'Delivered' },
    ],
    recentPurchases: [
      { id: 'pur-5', name: 'Premium Modal Hijab', price: 90, imageUrl: 'https://picsum.photos/seed/purchase-5/120/120' },
      { id: 'pur-6', name: 'Chiffon Hijab Set', price: 140, imageUrl: 'https://picsum.photos/seed/purchase-6/120/120' },
    ],
  },
  {
    id: 'cust-zahra-mansour',
    name: 'Zahra Mansour',
    email: 'zahra@outlook.com',
    avatarUrl: 'https://picsum.photos/seed/customer-zahra/64/64',
    status: 'New',
    ordersCount: 1,
    totalSpent: 350,
    lastOrderDate: 'Nov 12, 2023',
    memberSince: 'Nov 2023',
    shippingAddress: ['19 Jalan Maarof', 'Bangsar, Kuala Lumpur', 'Malaysia'],
    notes: ['First purchase from Instagram campaign.'],
    orderHistory: [{ id: '#AT-94011', date: 'Nov 12, 2023', total: 350, paymentStatus: 'Paid', fulfillmentStatus: 'Processing' }],
    recentPurchases: [{ id: 'pur-7', name: 'Silk Evening Abaya', price: 350, imageUrl: 'https://picsum.photos/seed/purchase-7/120/120' }],
  },
  {
    id: 'cust-aisha-ibrahim',
    name: 'Aisha Ibrahim',
    email: 'a.ibr@gmail.com',
    avatarUrl: 'https://picsum.photos/seed/customer-aisha/64/64',
    status: 'VIP',
    ordersCount: 24,
    totalSpent: 28110,
    lastOrderDate: 'Nov 29, 2023',
    memberSince: 'Jan 2023',
    shippingAddress: ['8 Marina Boulevard', 'Abu Dhabi', 'UAE'],
    notes: ['High-value repeat buyer.', 'Requests premium packaging.'],
    orderHistory: [
      { id: '#AT-95021', date: 'Nov 29, 2023', total: 1800, paymentStatus: 'Paid', fulfillmentStatus: 'Shipped' },
      { id: '#AT-94402', date: 'Nov 18, 2023', total: 1200, paymentStatus: 'Paid', fulfillmentStatus: 'Delivered' },
    ],
    recentPurchases: [
      { id: 'pur-8', name: 'Luxury Abaya Set', price: 620, imageUrl: 'https://picsum.photos/seed/purchase-8/120/120' },
      { id: 'pur-9', name: 'Premium Shawl', price: 210, imageUrl: 'https://picsum.photos/seed/purchase-9/120/120' },
    ],
  },
];

export const initialReviews: ReviewRecord[] = [
  {
    id: 'rev-1',
    customerId: 'cust-amara-al-said',
    customerName: 'Amara Al-Said',
    customerEmail: 'amara@atelier.com',
    productName: 'Silk Evening Abaya',
    productImageUrl: 'https://picsum.photos/seed/review-product-1/64/64',
    rating: 5,
    excerpt: 'The quality is excellent...',
    fullReview: 'The quality of the silk is exceptional. It drapes beautifully and feels incredibly luxurious.',
    status: 'Pending',
    date: 'Oct 24, 2023',
    verifiedPurchase: true,
  },
  {
    id: 'rev-2',
    customerId: 'cust-zahra-mansour',
    customerName: 'Zahra K.',
    customerEmail: 'zahra.k@email.com',
    productName: 'Linen Essential Dress',
    productImageUrl: 'https://picsum.photos/seed/review-product-2/64/64',
    rating: 4,
    excerpt: 'Perfect for daily wear...',
    fullReview: 'Perfect for daily wear and very breathable in warm weather.',
    status: 'Featured',
    date: 'Oct 21, 2023',
    verifiedPurchase: true,
  },
  {
    id: 'rev-3',
    customerId: 'cust-fatima-noor',
    customerName: 'Mariam A.',
    customerEmail: 'mariam@email.com',
    productName: 'Premium Modal Hijab',
    productImageUrl: 'https://picsum.photos/seed/review-product-3/64/64',
    rating: 5,
    excerpt: 'Very breathable...',
    fullReview: 'Very breathable and soft. Color looks exactly as shown.',
    status: 'Approved',
    date: 'Oct 18, 2023',
    verifiedPurchase: true,
  },
  {
    id: 'rev-4',
    customerId: 'cust-aisha-ibrahim',
    customerName: 'S. Fatima',
    customerEmail: 's.fatima@email.com',
    productName: 'Floral Kaftan',
    productImageUrl: 'https://picsum.photos/seed/review-product-4/64/64',
    rating: 1,
    excerpt: 'Shipping took too long.',
    fullReview: 'Shipping took too long and the box arrived slightly damaged.',
    status: 'Hidden',
    date: 'Oct 15, 2023',
    verifiedPurchase: false,
  },
];
