import type {
  AbandonedCheckout,
  AutomationRule,
  BroadcastCampaign,
  CampaignPerformance,
  DiscountCampaign,
  FunnelStepNode,
  MarketingMetric,
  UpsellOffer,
} from './types';

export const overviewMetrics: MarketingMetric[] = [
  { label: 'Discount Revenue', value: 'RM 124,500', helper: '+12.4% vs last month', trend: '+12.4%', trendDirection: 'up' },
  { label: 'Upsell Revenue', value: 'RM 42,100', helper: '+8.2% vs last month', trend: '+8.2%', trendDirection: 'up' },
  { label: 'Recovery Rate', value: '28.4%', helper: '-1.8% vs last month', trend: '-1.8%', trendDirection: 'down' },
  { label: 'Broadcast Revenue', value: 'RM 65,800', helper: '+6.4% vs last month', trend: '+6.4%', trendDirection: 'up' },
];

export const topCampaigns: CampaignPerformance[] = [
  {
    id: 'camp-raya-1',
    name: 'Ramadan Luxe Edit',
    type: 'Email',
    reach: 12450,
    clicks: 520,
    conversionRate: 4.8,
    revenue: 24180,
    imageUrl: 'https://picsum.photos/seed/marketing-raya/80/80',
  },
  {
    id: 'camp-eid-2',
    name: 'Eid Gifting Guide',
    type: 'WhatsApp',
    reach: 8900,
    clicks: 420,
    conversionRate: 6.2,
    revenue: 18430,
    imageUrl: 'https://picsum.photos/seed/marketing-eid/80/80',
  },
  {
    id: 'camp-flash-3',
    name: 'Midnight Abaya Flash Sale',
    type: 'Push + Email',
    reach: 25000,
    clicks: 930,
    conversionRate: 3.4,
    revenue: 32900,
    imageUrl: 'https://picsum.photos/seed/marketing-flash/80/80',
  },
];

export const discountsSeed: DiscountCampaign[] = [
  {
    id: 'disc-1',
    code: 'FIRST20',
    type: 'Percentage',
    value: 20,
    audience: 'First-Time Purchase',
    codeAccess: 'Public',
    deliveryChannels: [],
    usage: 55,
    usageCap: 100,
    status: 'Active',
    isEnabled: true,
    startsAt: '2026-04-01T09:00',
    endsAt: '2026-05-31T23:59',
    appliesTo: 'All Products',
    minimumRequirementType: 'None',
    customerEligibility: 'Everyone',
    usageLimitTotalEnabled: true,
    usageLimitPerCustomerEnabled: false,
    hasEndDate: true,
  },
  {
    id: 'disc-2',
    code: 'RAMADAN2026',
    type: 'Fixed',
    value: 50,
    audience: 'All Customers',
    codeAccess: 'Direct Code',
    deliveryChannels: ['WhatsApp', 'Email'],
    usage: 330,
    usageCap: 500,
    status: 'Scheduled',
    isEnabled: true,
    startsAt: '2026-05-10T00:00',
    endsAt: '2026-06-15T23:59',
    appliesTo: 'Specific Categories',
    minimumRequirementType: 'Minimum Purchase Amount',
    minimumRequirementValue: 200,
    customerEligibility: 'Everyone',
    usageLimitTotalEnabled: true,
    usageLimitPerCustomerEnabled: true,
    usageLimitPerCustomer: 1,
    hasEndDate: true,
  },
  {
    id: 'disc-3',
    code: 'RAYA15',
    type: 'Percentage',
    value: 15,
    audience: 'Returning Customers',
    codeAccess: 'Direct Code',
    deliveryChannels: ['Email'],
    usage: 0,
    usageCap: 200,
    status: 'Expired',
    isEnabled: false,
    startsAt: '2026-03-20T00:00',
    endsAt: '2026-04-10T23:59',
    appliesTo: 'All Products',
    minimumRequirementType: 'None',
    customerEligibility: 'Specific Customer',
    customerTarget: 'VIP Segment',
    usageLimitTotalEnabled: true,
    usageLimitPerCustomerEnabled: true,
    usageLimitPerCustomer: 1,
    hasEndDate: true,
  },
];

export const upsellsSeed: UpsellOffer[] = [
  {
    id: 'upsell-1',
    name: 'Premium Silk Ready Bundle',
    type: 'Bump Offer',
    trigger: 'Cart Checkout',
    conversionRate: 16.2,
    revenue: 4320,
    status: 'Active',
    imageUrl: 'https://picsum.photos/seed/upsell-bundle/72/72',
  },
  {
    id: 'upsell-2',
    name: 'Linen Eid Tote Leather Finish',
    type: 'One-Time Offer',
    trigger: 'Post Purchase',
    conversionRate: 9.4,
    revenue: 12195,
    status: 'Active',
    imageUrl: 'https://picsum.photos/seed/upsell-tote/72/72',
  },
  {
    id: 'upsell-3',
    name: 'Essential Collection Upgrade',
    type: 'Bump Offer',
    trigger: 'Cart Checkout',
    conversionRate: 6.0,
    revenue: 4890,
    status: 'Draft',
    imageUrl: 'https://picsum.photos/seed/upsell-upgrade/72/72',
  },
];

export const recoverySeed: AbandonedCheckout[] = [
  {
    id: 'CHK-7781',
    customer: 'Layla Ahmad',
    email: 'layla@example.com',
    cartValue: 580,
    cartItems: 2,
    lastActivity: '37 mins ago',
    status: 'Pending',
    imageUrl: 'https://picsum.photos/seed/recovery-1/72/72',
  },
  {
    id: 'CHK-7762',
    customer: 'Zarah Al-Yusof',
    email: 'zarah@example.com',
    cartValue: 420,
    cartItems: 1,
    lastActivity: '1 hour ago',
    status: 'Contacted',
    imageUrl: 'https://picsum.photos/seed/recovery-2/72/72',
  },
  {
    id: 'CHK-7728',
    customer: 'Mariam O.',
    email: 'mariam@example.com',
    cartValue: 890,
    cartItems: 3,
    lastActivity: 'Yesterday',
    status: 'Recovered',
    imageUrl: 'https://picsum.photos/seed/recovery-3/72/72',
  },
];

export const broadcastsSeed: BroadcastCampaign[] = [
  {
    id: 'bc-1',
    name: 'Ramadan Collection Launch',
    channel: 'Email',
    audience: 'VIP Segment',
    schedule: 'Apr 21, 2026 09:00 AM',
    openRate: 32.5,
    clickRate: 8.4,
    revenue: 33100,
    status: 'Sent',
  },
  {
    id: 'bc-2',
    name: 'VIP Early Access Raya 26',
    channel: 'WhatsApp',
    audience: 'High AOV',
    schedule: 'Apr 24, 2026 08:30 AM',
    openRate: 56.2,
    clickRate: 13.2,
    revenue: 72100,
    status: 'Scheduled',
  },
  {
    id: 'bc-3',
    name: 'Post-Purchase Care Guide',
    channel: 'Email',
    audience: 'Recent Buyers',
    schedule: 'Draft',
    openRate: 0,
    clickRate: 0,
    revenue: 0,
    status: 'Draft',
  },
];

export const funnelStepsSeed: FunnelStepNode[] = [
  { id: 'step-landing', label: 'Landing Page', type: 'page', conversionRate: 72.6, status: 'active' },
  { id: 'step-checkout', label: 'Checkout', type: 'page', conversionRate: 48.2, status: 'active' },
  { id: 'step-oto', label: 'One-Time Offer', type: 'offer', conversionRate: 14.8, status: 'active' },
  { id: 'step-downsell', label: 'Downsell', type: 'offer', conversionRate: 8.5, status: 'optional' },
  { id: 'step-thankyou', label: 'Thank You Page', type: 'page', conversionRate: 100, status: 'active' },
];

export const automationRulesSeed: AutomationRule[] = [
  {
    id: 'rule-1',
    name: 'High Intent Upsell Boost',
    priority: 'High',
    condition: 'Cart Value > RM150 and Returning Customer',
    action: 'Show OTO A with 24% discount',
    estUplift: 14.8,
    status: 'Active',
  },
  {
    id: 'rule-2',
    name: 'Cart Recovery Logic',
    priority: 'Medium',
    condition: 'No checkout after 30 minutes',
    action: 'Send WhatsApp reminder then email fallback',
    estUplift: 8.2,
    status: 'Draft',
  },
];
