import { Archive, Boxes, Package, Tags } from 'lucide-react';
import type { Category, KpiMetric, Product } from './types';

export const products: Product[] = [
  {
    id: 'prod-abaya-silk',
    title: 'Silk Evening Abaya',
    sku: 'ABY-SLK-004',
    categoryId: 'cat-evening',
    categoryName: 'Evening Collection',
    price: 360,
    stock: 18,
    status: 'Active',
    stockState: 'In Stock',
    thumbnailUrl: 'https://picsum.photos/seed/product-abaya/120/120',
    description: 'Premium silk abaya for formal events and evening occasions.',
    vendor: 'Bisora',
    productType: 'Abaya',
    tags: ['silk', 'evening', 'premium'],
    seoTitle: 'Silk Evening Abaya | Bisora',
    seoDescription: 'Shop a premium silk evening abaya designed for elegant occasions.',
    slug: 'silk-evening-abaya',
    compareAtPrice: 430,
    taxable: true,
    manageStock: true,
    hasSku: true,
    isPhysical: true,
    weightKg: 0.9,
    packageProfile: 'Box',
    variants: [
      { id: 'var-abaya-black-s', name: 'Black / S', sku: 'ABY-SLK-004-BLK-S', price: 360, stock: 6, stockState: 'In Stock', lastUpdated: 'Apr 21, 2026' },
      { id: 'var-abaya-black-m', name: 'Black / M', sku: 'ABY-SLK-004-BLK-M', price: 360, stock: 4, stockState: 'Low Stock', lastUpdated: 'Apr 21, 2026' },
      { id: 'var-abaya-emerald-m', name: 'Emerald / M', sku: 'ABY-SLK-004-EMR-M', price: 380, stock: 8, stockState: 'In Stock', lastUpdated: 'Apr 20, 2026' },
    ],
  },
  {
    id: 'prod-hijab-modal',
    title: 'Premium Modal Hijab',
    sku: 'HJB-MDL-018',
    categoryId: 'cat-everyday',
    categoryName: 'Everyday Essentials',
    price: 90,
    stock: 42,
    status: 'Active',
    stockState: 'High Stock',
    thumbnailUrl: 'https://picsum.photos/seed/product-hijab/120/120',
    description: 'Breathable modal hijab with soft drape and everyday comfort.',
    vendor: 'Bisora',
    productType: 'Hijab',
    tags: ['modal', 'hijab', 'essentials'],
    seoTitle: 'Premium Modal Hijab | Bisora',
    seoDescription: 'Soft modal hijab made for daily wear and breathable comfort.',
    slug: 'premium-modal-hijab',
    compareAtPrice: 110,
    taxable: true,
    manageStock: true,
    hasSku: true,
    isPhysical: true,
    weightKg: 0.2,
    packageProfile: 'Pouch',
    variants: [
      { id: 'var-hijab-cream', name: 'Cream', sku: 'HJB-MDL-018-CRM', price: 90, stock: 16, stockState: 'In Stock', lastUpdated: 'Apr 21, 2026' },
      { id: 'var-hijab-sage', name: 'Sage', sku: 'HJB-MDL-018-SGE', price: 90, stock: 22, stockState: 'High Stock', lastUpdated: 'Apr 19, 2026' },
      { id: 'var-hijab-rose', name: 'Rose', sku: 'HJB-MDL-018-RSE', price: 90, stock: 4, stockState: 'Low Stock', lastUpdated: 'Apr 18, 2026' },
    ],
  },
  {
    id: 'prod-linen-dress',
    title: 'Linen Essential Dress',
    sku: 'DRS-LIN-212',
    categoryId: 'cat-everyday',
    categoryName: 'Everyday Essentials',
    price: 520,
    stock: 0,
    status: 'Unpublished',
    stockState: 'Out of Stock',
    thumbnailUrl: 'https://picsum.photos/seed/product-dress/120/120',
    description: 'Relaxed linen dress with modest cut for daily styling.',
    vendor: 'Bisora',
    productType: 'Dress',
    tags: ['linen', 'dress', 'daily'],
    seoTitle: 'Linen Essential Dress | Bisora',
    seoDescription: 'A relaxed linen dress designed for modest everyday styling.',
    slug: 'linen-essential-dress',
    compareAtPrice: 590,
    taxable: true,
    manageStock: true,
    hasSku: true,
    isPhysical: true,
    weightKg: 0.8,
    packageProfile: 'Box',
    variants: [
      { id: 'var-dress-xs', name: 'XS', sku: 'DRS-LIN-212-XS', price: 520, stock: 0, stockState: 'Out of Stock', lastUpdated: 'Apr 16, 2026' },
      { id: 'var-dress-s', name: 'S', sku: 'DRS-LIN-212-S', price: 520, stock: 0, stockState: 'Out of Stock', lastUpdated: 'Apr 16, 2026' },
    ],
  },
  {
    id: 'prod-wrap-chiffon',
    title: 'Chiffon Wrap Set',
    sku: 'WRP-CHF-022',
    categoryId: 'cat-evening',
    categoryName: 'Evening Collection',
    price: 445,
    stock: 9,
    status: 'Hidden',
    stockState: 'Low Stock',
    thumbnailUrl: 'https://picsum.photos/seed/product-wrap/120/120',
    description: 'Layered chiffon wrap set for curated occasion looks.',
    vendor: 'Bisora',
    productType: 'Wrap',
    tags: ['chiffon', 'wrap', 'occasion'],
    seoTitle: 'Chiffon Wrap Set | Bisora',
    seoDescription: 'A layered chiffon wrap set for polished occasion dressing.',
    slug: 'chiffon-wrap-set',
    compareAtPrice: 490,
    taxable: true,
    manageStock: true,
    hasSku: true,
    isPhysical: true,
    weightKg: 0.5,
    packageProfile: 'Pouch',
    variants: [
      { id: 'var-wrap-smoke', name: 'Smoke', sku: 'WRP-CHF-022-SMK', price: 445, stock: 5, stockState: 'Low Stock', lastUpdated: 'Apr 20, 2026' },
      { id: 'var-wrap-pearl', name: 'Pearl', sku: 'WRP-CHF-022-PRL', price: 445, stock: 4, stockState: 'Low Stock', lastUpdated: 'Apr 20, 2026' },
    ],
  },
];

export const categories: Category[] = [
  {
    id: 'cat-evening',
    name: 'Evening Collection',
    description: 'Curated occasion pieces for formal and festive looks.',
    status: 'Published',
    productIds: ['prod-abaya-silk', 'prod-wrap-chiffon'],
    coverUrl: 'https://picsum.photos/seed/category-evening/480/240',
    seoTitle: 'Evening Collection | Bisora',
    seoDescription: 'Shop elegant evening pieces for formal and festive occasions.',
    slug: 'evening-collection',
    health: 'Good',
  },
  {
    id: 'cat-everyday',
    name: 'Everyday Essentials',
    description: 'Daily modestwear staples for repeat styling.',
    status: 'Published',
    productIds: ['prod-hijab-modal', 'prod-linen-dress'],
    coverUrl: 'https://picsum.photos/seed/category-everyday/480/240',
    seoTitle: 'Everyday Essentials | Bisora',
    seoDescription: 'Discover everyday modestwear staples made for comfort.',
    slug: 'everyday-essentials',
    health: 'Needs SEO',
  },
  {
    id: 'cat-new-season',
    name: 'New Season',
    description: 'Fresh arrivals and campaign-led collection edits.',
    status: 'Hidden',
    productIds: [],
    coverUrl: 'https://picsum.photos/seed/category-season/480/240',
    seoTitle: 'New Season | Bisora',
    seoDescription: 'Explore new seasonal arrivals from Bisora.',
    slug: 'new-season',
    health: 'Needs Products',
  },
];

export const productKpiMetrics: KpiMetric[] = [
  { label: 'Total Products', value: String(products.length), helper: 'Catalog items', icon: Package },
  { label: 'Low Stock', value: String(products.filter((product) => product.stockState === 'Low Stock').length), helper: 'Needs stock review', icon: Archive },
  { label: 'Categories', value: String(categories.length), helper: 'Storefront collections', icon: Tags },
  { label: 'Variants', value: String(products.flatMap((product) => product.variants).length), helper: 'Inventory rows', icon: Boxes },
];
